export const USER_LOGGED_IN = "USER_LOGGED_IN"; 
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS";

export const USER_LIST_FETCH_BEGIN  = "USER_LIST_FETCH_BEGIN";
export const USER_LIST_FETCH_SUCCESS = "USER_LIST_FETCH_SUCCESS";
export const USER_LIST_FETCH_FAILURE = "USER_LIST_FETCH_FAILURE"; 

export const USER_DETAILS_FETCH_SUCCESS = "USER_DETAILS_FETCH_SUCCESS";
export const USER_LIKE_SUCCESS = "USER_LIKE_SUCCESS";
export const USER_LIKE_FAILURE = "USER_LIKE_FAILURE";